Implement reproducible container build process
openenclave/openenclave-build pull request #1
Opened 2019-11-11 21:36 UTC by yakman2020

2019-11-14 19:40 UTC, BRMcLaren reviewed
There is a lot of commented out code, making this difficult to review and follow.

2019-11-14 19:40 UTC, BRMcLaren commented on Docker/Dockerfile.bootstrap
> +ADD ubuntu-base-18.04.3-base-amd64.tar.gz  /
Where is this coming from? 

How do we know it has not been altered and how can external users check the build process this image has gone through.

Edit: it comes from a script generated locally.

2019-11-14 19:40 UTC, BRMcLaren commented on Docker/Dockerfile.bootstrap
> +ADD https://oedownload.blob.core.windows.net/oe-build/intel-sgx/libsgx-enclave-common-dev_2.7.100.4-bionic1_amd64.deb?st=2019-10-25T16%3A55%3A41Z&se=2020-10-26T16%3A55%3A00Z&sp=rl&sv=2018-03-28&sr=c&
How is this CDN secured and changes tracked?

Further, how are maintainers going to upload new drivers etc. in a secure way?

2019-11-14 19:40 UTC, BRMcLaren commented on Docker/Dockerfile.bootstrap
> +#ADD https://oebuildinfo.blob.core.windows.net/buildinfo/ubuntu-base-18.04.3-base-amd64.tar.gz.sig
This seems to be commented out?

2019-11-14 19:40 UTC, BRMcLaren commented on Docker/Dockerfile.bootstrap
> +# 2Do: setup CDN and build dummy
ToDo

2019-11-14 19:40 UTC, BRMcLaren commented on Docker/Dockerfile.bootstrap
> +ADD https://github.com/Kitware/CMake/releases/download/v3.15.1/cmake-3.15.1.tar.gz  /tmp/cmake-3.15.1.tar.gz
I was under the impression that Github was not a secure source, it uses SHA-1 and we probably do not want to use this as a source.

2019-11-14 19:40 UTC, BRMcLaren commented on Docker/Dockerfile.bootstrap
> +# 2do: Get this file from CDN and check signature
TODO

2019-11-14 19:54 UTC, BRMcLaren commented on Docker/Dockerfile.bootstrap
> +#RUN tar xvfz cmake-3.15.1-Linux-x86_64.tar.gz
This seems to be commented out, what is the impact of including it?

2019-11-14 23:37 UTC, BRMcLaren commented
I am having trouble following what steps need to be run.
I create the bootstrap image with build_bootstrap.sh...
I try to build the toolchain and then 

`brmclare@cdpxTest:~/openenclave-build/Docker$ ./build_toolchain.sh 
gpg: can't open '/tmp/tstellar-gpg-key.asc': No such file or directory
gpg: Total number processed: 0
could not verify signature  /tmp/cfe-7.1.0.src.tar.xz.sig
~/openenclave-build/Docker ~/openenclave-build/Docker
rm: cannot remove '/src/cmake-3.15.1/CMakeCache.txt': No such file or directory
rm: cannot remove '/build/cmake-3.15.1/CMakeCache.txt': No such file or directory`

Which then deleted everything...

I spent a few hours code reviewing this and clarification is needed.

Can you please add the rest of the documentation?
Can you please add the design documentation, as this needs to be reviewed?
Can you clarify why there is a Docker folder which includes everything, being checked in?
Please, include the DockerFile that runs this step by step to generate.
Please, update the code to not include commented out sections.
Please, clarify how we get the code sources into the blobs in a secure manner and how this is double-checked against the hashes when downloaded?

2019-11-14 23:38 UTC, BRMcLaren requested changes

2019-11-14 23:38 UTC, BRMcLaren commented on Docker/Dockerfile.bootstrap
> +#RUN tar xvfJ /tmp/clang+llvm-7.0.1-x86_64-linux-gnu-ubuntu-18.04.tar.xz
There is a lot of commented out code here, does this need to be included?

2019-11-14 23:38 UTC, BRMcLaren commented on Docker/Dockerfile.bootstrap
> +# Check the signature, build then check the sha256 hash of the binaries
Checking the signature?

2019-11-19 18:16 UTC, yakman2020 commented on Docker/Dockerfile.bootstrap
> +ADD ubuntu-base-18.04.3-base-amd64.tar.gz  /
Correct. It gets downloaded by the script "build_bootstrap.sh" from our CDN.  The reason a script is needed is that we don't trust dockerhub.

2019-11-19 18:17 UTC, yakman2020 commented on Docker/Dockerfile.bootstrap
> +ADD https://oedownload.blob.core.windows.net/oe-build/intel-sgx/libsgx-enclave-common-dev_2.7.100.4-bionic1_amd64.deb?st=2019-10-25T16%3A55%3A41Z&se=2020-10-26T16%3A55%3A00Z&sp=rl&sv=2018-03-28&sr=c&
Access is controlled by an SAS.  The write access is currently only me, but we can add a role for updateds via the portal.

2019-11-19 18:18 UTC, yakman2020 commented on Docker/Dockerfile.bootstrap
> +ADD https://github.com/Kitware/CMake/releases/download/v3.15.1/cmake-3.15.1.tar.gz  /tmp/cmake-3.15.1.tar.gz
We don't like depending on github. This should be a tar file from the CDN.

2020-03-26 21:50 UTC, closed without merging